/**
 * Integration unit tests for Phase 2B — Verified Place Catalog to Gemini Generation.
 *
 * Verifies all 14 required Phase 2B integration rules:
 * 1. Destination is resolved before Gemini.
 * 2. Catalog is built before Gemini.
 * 3. Gemini receives verified catalog data.
 * 4. Gemini receives internal place IDs (VP_01, VP_02, ...).
 * 5. Gemini prompt explicitly forbids invented places.
 * 6. A catalog containing 2 attractions does not require 5.
 * 7. Zero accommodation results do not produce fictional accommodation.
 * 8. Restaurant names come from catalog data.
 * 9. Place names/IDs remain associated (verifiedPlaceId, morningPlaceId).
 * 10. Nearby/nearest_town relation is preserved.
 * 11. No fake INR hotel price is generated by this integration.
 * 12. Existing TravelPlan parsing still works.
 * 13. Gemini failure does not invoke a fictional-place fallback (uses grounded fallback).
 * 14. Existing non-place fields continue working (weatherAdvice, budgetTips).
 *
 * All external calls (Google and Gemini) are mocked; zero live API calls are made.
 */

import assert from 'node:assert/strict';
import { GeneratePlanRequest, TravelPlan } from './src/types.js';
import { ResolvedDestination } from './src/services/destinationResolver.js';
import {
  VerifiedPlaceCatalog,
  formatCatalogForPrompt
} from './src/services/placeCatalog.js';
import {
  generateTravelPlanService,
  generateCatalogGroundedFallback
} from './src/aiService.js';

let totalTests = 0;
let passedTests = 0;

function runTest(name: string, fn: () => void | Promise<void>) {
  totalTests++;
  try {
    const result = fn();
    if (result && typeof (result as any).then === 'function') {
      return (result as Promise<void>)
        .then(() => {
          passedTests++;
          console.log(`  [PASS] ${name}`);
        })
        .catch((err) => {
          console.error(`  [FAIL] ${name}:`, err.message);
          throw err;
        });
    } else {
      passedTests++;
      console.log(`  [PASS] ${name}`);
      return Promise.resolve();
    }
  } catch (err: any) {
    console.error(`  [FAIL] ${name}:`, err.message);
    throw err;
  }
}

// Sample rural destination anchor: Chandekasare
const mockRuralDestination: ResolvedDestination = {
  originalInput: 'Chandekasare',
  canonicalName: 'Chandekasare',
  formattedAddress: 'Chandekasare, Maharashtra 423601, India',
  latitude: 19.8654,
  longitude: 74.4812,
  providerPlaceId: 'ChIJ_chandekasare_anchor',
  locationType: 'APPROXIMATE',
  addressComponents: [
    { longName: 'Chandekasare', shortName: 'Chandekasare', types: ['locality'] },
    { longName: 'Maharashtra', shortName: 'MH', types: ['administrative_area_level_1'] }
  ]
};

// Rural catalog: 0 accommodations, 1 attraction, 2 restaurants
const mockRuralCatalog: VerifiedPlaceCatalog = {
  destination: mockRuralDestination,
  places: [
    {
      internalId: 'VP_01',
      provider: 'google_places',
      providerPlaceId: 'ChIJ_temple_01',
      name: 'Shri Ram Mandir Chandekasare',
      primaryCategory: 'attraction',
      types: ['hindu_temple', 'place_of_worship'],
      formattedAddress: 'Gram Panchayat Road, Chandekasare',
      location: { latitude: 19.8658, longitude: 74.4816 },
      distanceMeters: 250,
      localityRelation: 'exact_destination',
      rating: 4.7,
      userRatingCount: 45,
      googleMapsUri: 'https://maps.google.com/?cid=111',
      websiteUri: null,
      phoneNumber: null,
      openingHours: ['Monday: 6:00 AM - 9:00 PM'],
      priceLevel: null,
      priceStatus: 'PRICE_UNAVAILABLE',
      estimatedPriceInrRange: null,
      verificationTimestamp: '2026-10-08T00:00:00.000Z'
    },
    {
      internalId: 'VP_02',
      provider: 'google_places',
      providerPlaceId: 'ChIJ_dhaba_01',
      name: 'Kisan Dhaba',
      primaryCategory: 'restaurant',
      types: ['restaurant'],
      formattedAddress: 'Shirdi-Manmad Highway',
      location: { latitude: 19.8100, longitude: 74.4700 },
      distanceMeters: 6200,
      localityRelation: 'nearby',
      rating: 4.1,
      userRatingCount: 110,
      googleMapsUri: 'https://maps.google.com/?cid=222',
      websiteUri: null,
      phoneNumber: '02423 200 300',
      openingHours: null,
      priceLevel: 'PRICE_LEVEL_INEXPENSIVE',
      priceStatus: 'PRICE_LEVEL_ONLY',
      estimatedPriceInrRange: null,
      verificationTimestamp: '2026-10-08T00:00:00.000Z'
    },
    {
      internalId: 'VP_03',
      provider: 'google_places',
      providerPlaceId: 'ChIJ_dhaba_02',
      name: 'Sai Prasad Pure Veg',
      primaryCategory: 'restaurant',
      types: ['restaurant'],
      formattedAddress: 'Highway Toll Naka',
      location: { latitude: 19.7900, longitude: 74.4700 },
      distanceMeters: 8400,
      localityRelation: 'nearby',
      rating: 3.9,
      userRatingCount: 50,
      googleMapsUri: 'https://maps.google.com/?cid=333',
      websiteUri: null,
      phoneNumber: null,
      openingHours: null,
      priceLevel: null,
      priceStatus: 'PRICE_UNAVAILABLE',
      estimatedPriceInrRange: null,
      verificationTimestamp: '2026-10-08T00:00:00.000Z'
    }
  ],
  byCategory: {
    accommodation: [], // Zero hotels in village
    attraction: [
      {
        internalId: 'VP_01',
        provider: 'google_places',
        providerPlaceId: 'ChIJ_temple_01',
        name: 'Shri Ram Mandir Chandekasare',
        primaryCategory: 'attraction',
        types: ['hindu_temple'],
        formattedAddress: 'Gram Panchayat Road, Chandekasare',
        location: { latitude: 19.8658, longitude: 74.4816 },
        distanceMeters: 250,
        localityRelation: 'exact_destination',
        rating: 4.7,
        userRatingCount: 45,
        googleMapsUri: null,
        websiteUri: null,
        phoneNumber: null,
        openingHours: null,
        priceLevel: null,
        priceStatus: 'PRICE_UNAVAILABLE',
        estimatedPriceInrRange: null,
        verificationTimestamp: '2026-10-08T00:00:00.000Z'
      }
    ],
    restaurant: [
      {
        internalId: 'VP_02',
        provider: 'google_places',
        providerPlaceId: 'ChIJ_dhaba_01',
        name: 'Kisan Dhaba',
        primaryCategory: 'restaurant',
        types: ['restaurant'],
        formattedAddress: 'Shirdi-Manmad Highway',
        location: { latitude: 19.8100, longitude: 74.4700 },
        distanceMeters: 6200,
        localityRelation: 'nearby',
        rating: 4.1,
        userRatingCount: 110,
        googleMapsUri: null,
        websiteUri: null,
        phoneNumber: null,
        openingHours: null,
        priceLevel: 'PRICE_LEVEL_INEXPENSIVE',
        priceStatus: 'PRICE_LEVEL_ONLY',
        estimatedPriceInrRange: null,
        verificationTimestamp: '2026-10-08T00:00:00.000Z'
      },
      {
        internalId: 'VP_03',
        provider: 'google_places',
        providerPlaceId: 'ChIJ_dhaba_02',
        name: 'Sai Prasad Pure Veg',
        primaryCategory: 'restaurant',
        types: ['restaurant'],
        formattedAddress: 'Highway Toll Naka',
        location: { latitude: 19.7900, longitude: 74.4700 },
        distanceMeters: 8400,
        localityRelation: 'nearby',
        rating: 3.9,
        userRatingCount: 50,
        googleMapsUri: null,
        websiteUri: null,
        phoneNumber: null,
        openingHours: null,
        priceLevel: null,
        priceStatus: 'PRICE_UNAVAILABLE',
        estimatedPriceInrRange: null,
        verificationTimestamp: '2026-10-08T00:00:00.000Z'
      }
    ],
    activity: [],
    poi: []
  },
  metadata: {
    generatedAt: '2026-10-08T00:00:00.000Z',
    searchRadiiMeters: [5000, 15000, 25000],
    totalVerifiedPlaces: 3
  }
};

const sampleRequest: GeneratePlanRequest = {
  destination: 'Chandekasare',
  numberOfDays: 2,
  budgetInr: 10000,
  numberOfTravellers: 2,
  interests: ['Local Sightseeing', 'Cultural Heritage'],
  accommodationPreference: 'Moderate',
  activityLevel: 'Relaxed'
};

async function runAllTests() {
  console.log('\n--- 1. Testing Grounded Catalog Prompt Serialization ---');

  await runTest('3, 4, 10. formatCatalogForPrompt serializes internal IDs, names, and locality distances', () => {
    const formatted = formatCatalogForPrompt(mockRuralCatalog);

    assert.ok(formatted.includes('Destination Anchor: Chandekasare'));
    assert.ok(formatted.includes('[ACCOMMODATION (0 verified found)]:'));
    assert.ok(formatted.includes('(None found within 25 km of destination)'));
    assert.ok(formatted.includes('ID: VP_01'));
    assert.ok(formatted.includes('Name: "Shri Ram Mandir Chandekasare"'));
    assert.ok(formatted.includes('Locality: exact_destination (~0.3 km from anchor)'));
    assert.ok(formatted.includes('ID: VP_02'));
    assert.ok(formatted.includes('Name: "Kisan Dhaba"'));
    assert.ok(formatted.includes('Locality: nearby (~6.2 km from anchor)'));
  });

  console.log('\n--- 2. Testing Grounded Fallback Engine (No Fake Places) ---');

  await runTest('6, 7, 8, 11, 13, 14. Grounded fallback uses ONLY verified places and fabricates zero entities', () => {
    const fallbackPlan = generateCatalogGroundedFallback(sampleRequest, mockRuralCatalog);

    // Rule 6: 1 attraction exists -> exactly 1 in placesToVisit (never fabricates 5)
    assert.equal(fallbackPlan.placesToVisit.length, 1);
    assert.equal(fallbackPlan.placesToVisit[0].verifiedPlaceId, 'VP_01');
    assert.equal(fallbackPlan.placesToVisit[0].name, 'Shri Ram Mandir Chandekasare');

    // Rule 7: Zero accommodations -> honest guidance, NO fake hotels
    assert.ok(
      fallbackPlan.accommodationGuidance.includes('No verified commercial accommodation options were found'),
      'Must honestly declare no verified accommodations'
    );
    assert.ok(!fallbackPlan.accommodationGuidance.includes('Hotel Shanti'));
    assert.ok(!fallbackPlan.accommodationGuidance.includes('Local Inn'));

    // Rule 8: Restaurants come from catalog
    assert.equal(fallbackPlan.foodAndLocalExperiences.length, 2);
    assert.equal(fallbackPlan.foodAndLocalExperiences[0].verifiedPlaceId, 'VP_02');
    assert.equal(fallbackPlan.foodAndLocalExperiences[0].name, 'Kisan Dhaba');
    assert.equal(fallbackPlan.foodAndLocalExperiences[1].verifiedPlaceId, 'VP_03');
    assert.equal(fallbackPlan.foodAndLocalExperiences[1].name, 'Sai Prasad Pure Veg');

    // Rule 9: Itinerary links morning and afternoon place IDs
    assert.equal(fallbackPlan.itinerary.length, 2);
    assert.equal(fallbackPlan.itinerary[0].morningPlaceId, 'VP_01');
    assert.equal(fallbackPlan.itinerary[0].afternoonPlaceId, 'VP_02');
    assert.equal(fallbackPlan.itinerary[1].afternoonPlaceId, 'VP_03');

    // Rule 11: No fake nightly hotel price generated
    for (const tip of fallbackPlan.budgetTips) {
      assert.ok(!tip.includes('₹1,500/night'));
      assert.ok(!tip.includes('/night at local inn'));
    }

    // Rule 14: Non-place fields exist and work
    assert.ok(fallbackPlan.weatherAdvice.length > 0);
    assert.ok(fallbackPlan.budgetTips.length > 0);
    assert.equal(fallbackPlan.resolvedDestination?.canonicalName, 'Chandekasare');
    assert.equal(fallbackPlan.verifiedPlacesCatalog?.length, 3);
  });

  console.log('\n--- 3. Testing generateTravelPlanService Integration ---');

  await runTest('1, 2, 5, 9, 12. Full flow: Resolves destination, injects catalog, parses verifiedPlaceId', async () => {
    // Mock Gemini responding with JSON referencing the verified catalog IDs
    const mockGeminiResponse = JSON.stringify({
      accommodationGuidance: 'No commercial accommodations were verified within 25 km of Chandekasare. Stay in nearby Kopargaon (11 km) is recommended.',
      placesToVisit: [
        {
          verifiedPlaceId: 'VP_01',
          name: 'Shri Ram Mandir Chandekasare',
          reason: 'Historic spiritual landmark in the village center.',
          bestTime: 'Morning (07:00 AM)'
        }
      ],
      foodAndLocalExperiences: [
        {
          verifiedPlaceId: 'VP_02',
          name: 'Kisan Dhaba',
          reason: 'Authentic regional highway dining located ~6.2 km away.'
        }
      ],
      activities: [
        {
          name: 'Countryside Farmland Walk',
          reason: 'Scenic walking discovery of Chandekasare village.'
        }
      ],
      weatherAdvice: 'Pleasant weather; pack light breathable layers.',
      budgetTips: ['Allocate funds for local transit to Kopargaon.'],
      itinerary: [
        {
          day: 1,
          morning: 'Arrive in Chandekasare and visit [Shri Ram Mandir Chandekasare].',
          morningPlaceId: 'VP_01',
          afternoon: 'Head to [Kisan Dhaba] along the highway for regional lunch.',
          afternoonPlaceId: 'VP_02',
          evening: 'Leisurely evening stroll along the village farmland roads.',
          eveningPlaceId: null,
          notes: 'Carry cash for small shops.',
          alternative: 'Relax at your stay.'
        },
        {
          day: 2,
          morning: 'Morning walk around the village community square.',
          morningPlaceId: null,
          afternoon: 'Enjoy lunch at [Sai Prasad Pure Veg] (~8.4 km away).',
          afternoonPlaceId: 'VP_03',
          evening: 'Sunset reflections and departure preparations.',
          eveningPlaceId: null,
          notes: 'Verify bus timings.',
          alternative: 'Rest during peak afternoon.'
        }
      ]
    });

    // Mock fetch interceptor for both Google geocode/places and Gemini generateContent
    let capturedPrompt = '';
    const mockFetch: typeof fetch = async (url, init) => {
      const urlStr = String(url);

      if (urlStr.includes('generateContent')) {
        const body = JSON.parse(init?.body as string || '{}');
        capturedPrompt = body.contents?.[0]?.parts?.[0]?.text || '';
        return new Response(
          JSON.stringify({
            candidates: [
              {
                content: {
                  parts: [{ text: mockGeminiResponse }]
                }
              }
            ]
          }),
          { status: 200, headers: { 'Content-Type': 'application/json' } }
        );
      }

      // Geocoding mock
      if (urlStr.includes('geocode/json')) {
        return new Response(
          JSON.stringify({
            status: 'OK',
            results: [
              {
                place_id: 'ChIJ_chandekasare',
                formatted_address: 'Chandekasare, Maharashtra 423601, India',
                geometry: {
                  location: { lat: 19.8654, lng: 74.4812 },
                  location_type: 'APPROXIMATE'
                },
                address_components: [
                  { long_name: 'Chandekasare', short_name: 'Chandekasare', types: ['locality'] }
                ]
              }
            ]
          }),
          { status: 200, headers: { 'Content-Type': 'application/json' } }
        );
      }

      // Places API mock
      return new Response(JSON.stringify({ places: [] }), {
        status: 200,
        headers: { 'Content-Type': 'application/json' }
      });
    };

    // Set mock Gemini key
    process.env.GEMINI_API_KEY = 'test_mock_gemini_key';
    process.env.GOOGLE_MAPS_API_KEY = 'test_mock_maps_key';

    const result = await generateTravelPlanService(sampleRequest, {
      catalogOverride: mockRuralCatalog,
      fetchFn: mockFetch
    });

    // Rule 1 & 2: Prompt was captured and contains verified catalog
    assert.ok(capturedPrompt.includes('<verified_places_catalog>'), 'Prompt must contain verified catalog');
    assert.ok(capturedPrompt.includes('VP_01'), 'Prompt must include internalId VP_01');
    assert.ok(capturedPrompt.includes('Shri Ram Mandir Chandekasare'), 'Prompt must include place name');

    // Rule 5: Prompt explicitly forbids invented places
    assert.ok(capturedPrompt.includes('CRITICAL GROUNDING REQUIREMENT:'));
    assert.ok(capturedPrompt.includes('Do NOT invent any hotel, attraction, temple, restaurant'));

    // Rule 9 & 12: Parsed plan preserves verified place IDs and structure
    const plan = result.plan;
    assert.equal(plan.placesToVisit[0].verifiedPlaceId, 'VP_01');
    assert.equal(plan.placesToVisit[0].name, 'Shri Ram Mandir Chandekasare');
    assert.equal(plan.foodAndLocalExperiences[0].verifiedPlaceId, 'VP_02');
    assert.equal(plan.itinerary[0].morningPlaceId, 'VP_01');
    assert.equal(plan.itinerary[0].afternoonPlaceId, 'VP_02');
    assert.equal(plan.itinerary[1].afternoonPlaceId, 'VP_03');

    // Backward-compatible string fields remain intact
    assert.ok(typeof plan.itinerary[0].morning === 'string');
    assert.ok(typeof plan.itinerary[0].afternoon === 'string');
    assert.ok(typeof plan.itinerary[0].evening === 'string');
    assert.equal(plan.resolvedDestination?.canonicalName, 'Chandekasare');
    assert.equal(plan.verifiedPlacesCatalog?.length, 3);
  });

  await runTest('13. Gemini failure falls back to grounded catalog plan (NOT fake templates)', async () => {
    // Mock Gemini throwing HTTP 500 error
    const mockFetch: typeof fetch = async (url) => {
      const urlStr = String(url);
      if (urlStr.includes('generateContent')) {
        return new Response('Internal AI Error', { status: 500 });
      }
      return new Response(JSON.stringify({ places: [] }), { status: 200 });
    };

    process.env.GEMINI_API_KEY = 'test_mock_gemini_key';

    const result = await generateTravelPlanService(sampleRequest, {
      catalogOverride: mockRuralCatalog,
      fetchFn: mockFetch
    });

    assert.equal(result.isDemo, true);
    // Grounded fallback must be used, NOT the old template with fake places
    assert.equal(result.plan.placesToVisit.length, 1);
    assert.equal(result.plan.placesToVisit[0].name, 'Shri Ram Mandir Chandekasare');
    assert.ok(!result.plan.placesToVisit[0].name.includes('Iconic Landmark of'));
    assert.ok(!result.plan.placesToVisit.some((p) => p.name.includes('Old Town Heritage Quarter')));
  });

  console.log(`\n============================================================`);
  console.log(`All Phase 2B Integration Tests Passed! (${passedTests}/${totalTests})`);
  console.log(`============================================================\n`);
}

runAllTests().catch((err) => {
  console.error('\nTest suite execution failed:', err);
  process.exit(1);
});
